#!/bin/bash

echo "$CK_CC $CK_FLAGS_DYNAMIC_BIN ${CK_FLAGS_CREATE_ASM} -emit-llvm
      ${CK_FLAG_PREFIX_INCLUDE}../ ${CK_FLAG_PREFIX_VAR}BLIS ${CK_FLAG_PREFIX_VAR}BLIS_VERSION_STRING=0.8.0-9
      ${CK_FLAG_PREFIX_VAR}CK_HOST_OS_NAME2_LINUX=1 ${CK_FLAG_PREFIX_VAR}CK_HOST_OS_NAME_LINUX=1
      ${CK_FLAG_PREFIX_VAR}CK_TARGET_OS_NAME2_LINUX=1 ${CK_FLAG_PREFIX_VAR}CK_TARGET_OS_NAME_LINUX=1
      ${CK_FLAG_PREFIX_VAR}POSIX_C_SOURCE=200112L ${CK_FLAG_PREFIX_VAR}XOPENME
      ${CK_FLAG_PREFIX_INCLUDE}"/home/phesse/CK-TOOLS/lib-rtl-xopenme-0.3-gcc-9.3.0-linux-64/include"
      ${CK_FLAG_PREFIX_INCLUDE}"/usr/include" ${CK_FLAG_PREFIX_INCLUDE}"/home/phesse/CK-TOOLS/lib-blis-0.8.0-master-linux-64/blis/include/zen2"
      ../test_gemm.c"

$CK_CC $CK_FLAGS_DYNAMIC_BIN ${CK_FLAGS_CREATE_ASM} -emit-llvm ${CK_FLAG_PREFIX_INCLUDE}../ ${CK_FLAG_PREFIX_VAR}BLIS ${CK_FLAG_PREFIX_VAR}BLIS_VERSION_STRING=0.8.0-9 ${CK_FLAG_PREFIX_VAR}CK_HOST_OS_NAME2_LINUX=1 ${CK_FLAG_PREFIX_VAR}CK_HOST_OS_NAME_LINUX=1 ${CK_FLAG_PREFIX_VAR}CK_TARGET_OS_NAME2_LINUX=1 ${CK_FLAG_PREFIX_VAR}CK_TARGET_OS_NAME_LINUX=1 ${CK_FLAG_PREFIX_VAR}POSIX_C_SOURCE=200112L ${CK_FLAG_PREFIX_VAR}XOPENME ${CK_FLAG_PREFIX_INCLUDE}"/home/phesse/CK-TOOLS/lib-rtl-xopenme-0.3-gcc-9.3.0-linux-64/include" ${CK_FLAG_PREFIX_INCLUDE}"/usr/include" ${CK_FLAG_PREFIX_INCLUDE}"/home/phesse/CK-TOOLS/lib-blis-0.8.0-master-linux-64/blis/include/zen2" ../test_gemm.c
er=$?; if [ $er != 0 ]; then exit $er; fi
exit 0
